services:
  db:
    image: mysql:8.0
    container_name: todo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u${DB_USERNAME} -p${DB_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: '${SPRING_DATASOURCE_URL}'
      SPRING_DATASOURCE_USERNAME: '${DB_USERNAME}'
      SPRING_DATASOURCE_PASSWORD: '${DB_PASSWORD}'
      JWT_SECRET: '${JWT_SECRET}'
    depends_on:
      - db

volumes:
  db_data:
